In [51]:
### AUTOGRAD: AUTOMATIC DIFFERENTIATION

import torch

# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2, 2, requires_grad=True)
print(x)

# Do tensor operation
y = x + 2
print(y)

# y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)

# Do more operation on y
z = y*y*3
out = z.mean()
print(z, out)

print(x.requires_grad)

#.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

### Gradients ###
# Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.)).
out.backward()  # i.e  operation on torch.tensor(1.) i.e, in dy/dx ==> x is 1

# Print gradients d(out)/dx
print('d(out)/dx = ',x.grad)

############################################
# x=torch.tensor(2.0, requires_grad=True)
# print(x)  
# y=8*x**4 + 3*x**3 + 7*x**2 + 6*x + 3  
# y.backward()  
# print('dy/dx  = ', x.grad) 
############################################

# Now let’s take a look at an example of vector-Jacobian product:

x = torch.randn(3, requires_grad=True)
y = x*2
print(y)
while y.data.norm() < 1000:
  y = y*2 
print(y)

# Now in this case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to backward as argument:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

# You can also stop autograd from tracking history on Tensors with .requires_grad=True either by wrapping the code block in with torch.no_grad():
print(x.requires_grad)
print( (x **2 ).requires_grad)
with torch.no_grad():
  print( (x **2 ).requires_grad)

# Or by using .detach() to get a new Tensor with the same content but that does not require gradients:
print(x.requires_grad)
y = x.detach()
print(x.requires_grad)
print(y.requires_grad)
print(x.eq(y))
print(x.eq(y).all())

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
True
False
True
d(out)/dx =  tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([ 0.3197, -1.0480,  2.0792], grad_fn=<MulBackward0>)
tensor([ 163.7021, -536.5969, 1064.5380], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
True
True
False
True
True
False
tensor([True, True, True])
tensor(True)
