In [1]:
from __future__ import print_function
import torch
import numpy as np

x = torch.empty(5,3)
print(x)

x = torch.randn(5,3)
print(x)

x = torch.tensor([3.24, 5])
print(x)

x = x.new_ones(5,3, dtype=torch.double)    # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)  # override dtype!
print(x)                                    # result has the same size 

print(x.size())

y = torch.rand(5,3)
print(x+y)
print(torch.ones(4,4) + torch.ones_like(torch.ones(4,4)))
print(torch.add(x,y))

result = torch.empty(5,3)
print(result)
torch.add(x,y, out=result)
print(result)

# Addition: in-place
# add x to y
y.add(x)
print(y)
# ***NOTE :: Any operation that mutates a tensor in-place is post-fixed with an ``_``. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.  ***

print(x[:, 1])

### Resizing: If you want to resize/reshape tensor, you can use torch.view ####
x = torch.randn(4,4)
y = x.view(16)
print(y)
z = x.view(-1, 8)     # the size -1 is inferred from other dimensions
print(z)
print(x.size(), y.size(), z.size())

a = torch.arange(1, 16)
print(a)


# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

### NumPy Bridge ::: ###
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

### See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

### Converting NumPy Array to Torch Tensor ###
#See how changing the np array changed the Torch Tensor automatically

a  = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)
# *** NOTE : All the Tensors on the CPU except a CharTensor support converting to NumPy and back. *** #

### CUDA Tensors
# Tensors can be moved onto any device using the .to method. #

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  device = torch.device('cuda')
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to('cpu', torch.double))
else:
  print('cuda GPU is not available..')

tensor([[1.7201e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])
tensor([[-0.8533, -2.8618,  0.7062],
        [ 0.8210,  1.7726,  1.2756],
        [-1.3296,  0.3248, -0.0748],
        [ 1.0549,  0.0478,  0.2159],
        [-1.6172, -0.7876,  1.2344]])
tensor([3.2400, 5.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6209,  0.8220, -0.4887],
        [-0.8286, -0.3417, -0.1079],
        [ 0.5071, -0.1091,  0.9209],
        [-0.8612, -1.4694,  0.2869],
        [-0.3847,  1.1756,  0.3453]])
torch.Size([5, 3])
tensor([[ 0.8434,  0.8371,  0.3873],
        [-0.3823,  0.1815,  0.5889],
        [ 1.3245,  0.4214,  1.9161],
        [-0.7698, -0.7926,  1.0378],
        [-0.2274,  1.9385,  0.9585]])
tensor([[2., 2., 2., 2.],
        [